### ISSUE TITLE
Smogon Import Gen 1/2

### ISSUE THREAD

**Issue by soopercool101** [architdate/PKHeX-Plugins#48]
Currently the Smogon Import for the first two generations sets Stat XP to 0. This should instead be maxed to 65535 as this is the assumed default for all stats in these gens.

**Comment by architdate** [comment]
Are you talking about the EVs being able to be pushed to 65535? Sorry I don't quite understand the issue.

**Comment by Lusamine** [comment]
When you import a set like this:
```
Pidgeot
- Double-Edge
- Hyper Beam
- Mimic
- Mirror Move
```

Showdown automatically assumes it has maxed stat exp:
![image](https://user-images.githubusercontent.com/30205550/92391774-db418200-f0e2-11ea-816b-e6bd42f65dd4.png)

The same set imported with ALM in Gen 1-2 gives you 0 stat exp:
![image](https://user-images.githubusercontent.com/30205550/92391826-ee545200-f0e2-11ea-86bb-8e5660670f7d.png)

**Comment by architdate** [comment]
Should probably be fixed in base pkhex then? @kwsch ?

**Comment by kwsch** [comment]
Showdown Sets do not specify the format they were created for, so there is no context to imply that EVs should be set to 65535. It depends on what the `ShowdownSet` is applied to -- the PKM object.

I agree that they shouldn't say it's 252 EVs for a GBPKM; the games do `sqrt(u16)/4` instead of `u8/4`. The end result is still the same, as anything above 63504 yields the same stat boost as 63504.

**Comment by soopercool101** [comment]
Generating a generation 1 or 2 set now throws an error here, likely a base pkhex issue @kwsch 
![image](https://user-images.githubusercontent.com/35675593/93724303-c0e3bb80-fb5a-11ea-98c0-be594d3e7662.png)

**Comment by kwsch** [comment]
`pk` should never be null; I'd recommend turning on nullable checks in your project. Without seeing call stack or locals, that's all I can discern.

**Comment by soopercool101** [comment]
```
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.PKMConverter.ConvertToType(PKM pk, Type destType, String& comment) in C:\git\PKHeX\PKHeX.Core\PKM\Util\PKMConverter.cs:line 231
   at AutoModPlugins.ModLogic.GetRandomEncounter(PKM blank, ITrainerInfo tr, Int32 species) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\Enhancements\ModLogic.cs:line 117
   at AutoModPlugins.ModLogic.GetRandomEncounter(ITrainerInfo tr, Int32 species, PKM& pk) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\Enhancements\ModLogic.cs:line 95
   at PKHeX.Core.AutoMod.Legalizer.GetLegalFromSet(ITrainerInfo tr, IBattleTemplate set, PKM template, LegalizationResult& msg) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\AutoMod\Legalizer.cs:line 126
   at PKHeX.Core.AutoMod.Legalizer.ImportToExisting(SaveFile tr, IReadOnlyList`1 sets, IList`1 arr, Int32 start, Boolean overwrite) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\AutoMod\Legalizer.cs:line 70
   at AutoModPlugins.ShowdownSetLoader.ImportSetsToBoxes(IReadOnlyList`1 sets, Boolean replace) in C:\git\PKHeX-Plugins\AutoLegalityMod\GUI\ShowdownSetLoader.cs:line 107
   at AutoModPlugins.ShowdownSetLoader.Import(IReadOnlyList`1 sets) in C:\git\PKHeX-Plugins\AutoLegalityMod\GUI\ShowdownSetLoader.cs:line 62
   at AutoModPlugins.SmogonGenner.GenSmogonSets(PKM rough) in C:\git\PKHeX-Plugins\AutoLegalityMod\Plugins\SmogonGenner.cs:line 46
   at AutoModPlugins.SmogonGenner.SmogonGenning(Object sender, EventArgs e) in C:\git\PKHeX-Plugins\AutoLegalityMod\Plugins\SmogonGenner.cs:line 23
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.CoreLib.dll

PKHeX, Version=20.8.7.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.dll

System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.dll

System.Threading.Thread, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Thread.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Windows.Forms.dll

System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Extensions.dll

System.ComponentModel.Primitives, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.Primitives.dll

System.Drawing.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Drawing.Primitives.dll

System.Collections.Specialized, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Specialized.dll

System.Runtime.InteropServices, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.InteropServices.dll

System.Collections, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.dll

System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.dll

System.Diagnostics.TraceSource, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.TraceSource.dll

System.Diagnostics.Debug, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Debug.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.Core.dll

netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\netstandard.dll

System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.IO.FileSystem.dll

System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Drawing.Common.dll

Microsoft.Win32.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\Microsoft.Win32.Primitives.dll

System.ComponentModel.EventBasedAsync, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.EventBasedAsync.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\Accessibility.dll

System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Configuration.ConfigurationManager.dll

System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Linq.dll

System.ObjectModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ObjectModel.dll

System.Diagnostics.Process, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Process.dll

System.Resources.ResourceManager, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Resources.ResourceManager.dll

System.Collections.NonGeneric, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.NonGeneric.dll

System.Resources.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Resources.Extensions.dll

System.Memory, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Memory.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Drawing.dll

System.Buffers, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Buffers.dll

Microsoft.Win32.SystemEvents, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\Microsoft.Win32.SystemEvents.dll

System.ComponentModel.TypeConverter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.TypeConverter.dll

System.ComponentModel, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.dll

System.Xml.ReaderWriter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Xml.ReaderWriter.dll

System.Private.Xml, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.Xml.dll

System.Net.WebClient, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.WebClient.dll

System.Private.Uri, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.Uri.dll

System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Algorithms.dll

System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Text.Encoding.Extensions.dll

System.Security.Cryptography.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Primitives.dll

System.Diagnostics.Tools, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Tools.dll

System.Text.RegularExpressions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Text.RegularExpressions.dll

System.Runtime.Serialization.Formatters, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Serialization.Formatters.dll

System.Xml.XmlSerializer, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Xml.XmlSerializer.dll

System.Collections.Concurrent, Version=4.0.15.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Concurrent.dll

System.Threading.Timer, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Timer.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.Drawing.dll

System.Windows.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Windows.Extensions.dll

System.Net.Requests, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Requests.dll

System.Net.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Primitives.dll

System.Security.Principal, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Principal.dll

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\AutoModPlugins.dll

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\mscorlib.dll

System.Diagnostics.Tracing, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Tracing.dll

System.Net.WebHeaderCollection, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.WebHeaderCollection.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\PKHeX.Core.AutoMod.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.dll

System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Http.dll

FeebasLocatorPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\FeebasLocatorPlugin.dll

LibUsbDotNet.LibUsbDotNet, Version=2.2.0.0, Culture=neutral, PublicKeyToken=c677239abe1e02a9
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\LibUsbDotNet.LibUsbDotNet.dll

System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Tasks.dll

NtrSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\NtrSharp.dll

System.Security.Cryptography.X509Certificates, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.X509Certificates.dll

System.Net.ServicePoint, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.ServicePoint.dll

System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Security.dll

System.Runtime.Numerics, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Numerics.dll

System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.DiagnosticSource.dll

System.Net.Sockets, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Sockets.dll

System.Threading.Overlapped, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Overlapped.dll

System.Net.NameResolution, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.NameResolution.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Core.dll

System.Console, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Console.dll

System.Security.Principal.Windows, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Principal.Windows.dll

System.Security.Claims, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Claims.dll

System.Threading.ThreadPool, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.ThreadPool.dll

System.Security.Cryptography.Encoding, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Encoding.dll

System.Diagnostics.StackTrace, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.StackTrace.dll

System.Reflection.Metadata, Version=1.4.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Reflection.Metadata.dll

System.Collections.Immutable, Version=1.2.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Immutable.dll

System.IO.MemoryMappedFiles, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.IO.MemoryMappedFiles.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
Exception Details:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.PKMConverter.ConvertToType(PKM pk, Type destType, String& comment) in C:\git\PKHeX\PKHeX.Core\PKM\Util\PKMConverter.cs:line 231
   at AutoModPlugins.ModLogic.GetRandomEncounter(PKM blank, ITrainerInfo tr, Int32 species) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\Enhancements\ModLogic.cs:line 117
   at AutoModPlugins.ModLogic.GetRandomEncounter(ITrainerInfo tr, Int32 species, PKM& pk) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\Enhancements\ModLogic.cs:line 95
   at PKHeX.Core.AutoMod.Legalizer.GetLegalFromSet(ITrainerInfo tr, IBattleTemplate set, PKM template, LegalizationResult& msg) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\AutoMod\Legalizer.cs:line 126
   at PKHeX.Core.AutoMod.Legalizer.ImportToExisting(SaveFile tr, IReadOnlyList`1 sets, IList`1 arr, Int32 start, Boolean overwrite) in C:\git\PKHeX-Plugins\PKHeX.Core.AutoMod\AutoMod\Legalizer.cs:line 70
   at AutoModPlugins.ShowdownSetLoader.ImportSetsToBoxes(IReadOnlyList`1 sets, Boolean replace) in C:\git\PKHeX-Plugins\AutoLegalityMod\GUI\ShowdownSetLoader.cs:line 107
   at AutoModPlugins.ShowdownSetLoader.Import(IReadOnlyList`1 sets) in C:\git\PKHeX-Plugins\AutoLegalityMod\GUI\ShowdownSetLoader.cs:line 62
   at AutoModPlugins.SmogonGenner.GenSmogonSets(PKM rough) in C:\git\PKHeX-Plugins\AutoLegalityMod\Plugins\SmogonGenner.cs:line 46
   at AutoModPlugins.SmogonGenner.SmogonGenning(Object sender, EventArgs e) in C:\git\PKHeX-Plugins\AutoLegalityMod\Plugins\SmogonGenner.cs:line 23
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.CoreLib.dll

PKHeX, Version=20.8.7.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.dll

System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.dll

System.Threading.Thread, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Thread.dll

System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Windows.Forms.dll

System.Runtime.Extensions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Extensions.dll

System.ComponentModel.Primitives, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.Primitives.dll

System.Drawing.Primitives, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Drawing.Primitives.dll

System.Collections.Specialized, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Specialized.dll

System.Runtime.InteropServices, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.InteropServices.dll

System.Collections, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.dll

System.Threading, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.dll

System.Diagnostics.TraceSource, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.TraceSource.dll

System.Diagnostics.Debug, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Debug.dll

PKHeX.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.Core.dll

netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\netstandard.dll

System.IO.FileSystem, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.IO.FileSystem.dll

System.Drawing.Common, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Drawing.Common.dll

Microsoft.Win32.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\Microsoft.Win32.Primitives.dll

System.ComponentModel.EventBasedAsync, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.EventBasedAsync.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\Accessibility.dll

System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Configuration.ConfigurationManager.dll

System.Linq, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Linq.dll

System.ObjectModel, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ObjectModel.dll

System.Diagnostics.Process, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Process.dll

System.Resources.ResourceManager, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Resources.ResourceManager.dll

System.Collections.NonGeneric, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.NonGeneric.dll

System.Resources.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Resources.Extensions.dll

System.Memory, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Memory.dll

System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Drawing.dll

System.Buffers, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Buffers.dll

Microsoft.Win32.SystemEvents, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\Microsoft.Win32.SystemEvents.dll

System.ComponentModel.TypeConverter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.TypeConverter.dll

System.ComponentModel, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.ComponentModel.dll

System.Xml.ReaderWriter, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Xml.ReaderWriter.dll

System.Private.Xml, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.Xml.dll

System.Net.WebClient, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.WebClient.dll

System.Private.Uri, Version=4.0.6.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Private.Uri.dll

System.Security.Cryptography.Algorithms, Version=4.3.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Algorithms.dll

System.Text.Encoding.Extensions, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Text.Encoding.Extensions.dll

System.Security.Cryptography.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Primitives.dll

System.Diagnostics.Tools, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Tools.dll

System.Text.RegularExpressions, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Text.RegularExpressions.dll

System.Runtime.Serialization.Formatters, Version=4.0.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Serialization.Formatters.dll

System.Xml.XmlSerializer, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Xml.XmlSerializer.dll

System.Collections.Concurrent, Version=4.0.15.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Concurrent.dll

System.Threading.Timer, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Timer.dll

PKHeX.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\PKHeX.Drawing.dll

System.Windows.Extensions, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.1.8\System.Windows.Extensions.dll

System.Net.Requests, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Requests.dll

System.Net.Primitives, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Primitives.dll

System.Security.Principal, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Principal.dll

AutoModPlugins, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\AutoModPlugins.dll

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\mscorlib.dll

System.Diagnostics.Tracing, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.Tracing.dll

System.Net.WebHeaderCollection, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.WebHeaderCollection.dll

PKHeX.Core.AutoMod, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\PKHeX.Core.AutoMod.dll

System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.dll

System.Net.Http, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Http.dll

FeebasLocatorPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\FeebasLocatorPlugin.dll

LibUsbDotNet.LibUsbDotNet, Version=2.2.0.0, Culture=neutral, PublicKeyToken=c677239abe1e02a9
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\LibUsbDotNet.LibUsbDotNet.dll

System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Tasks.dll

NtrSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
C:\git\PKHeX\PKHeX.WinForms\bin\Release\netcoreapp3.1\plugins\NtrSharp.dll

System.Security.Cryptography.X509Certificates, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.X509Certificates.dll

System.Net.ServicePoint, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.ServicePoint.dll

System.Net.Security, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Security.dll

System.Runtime.Numerics, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Runtime.Numerics.dll

System.Diagnostics.DiagnosticSource, Version=4.0.5.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.DiagnosticSource.dll

System.Net.Sockets, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.Sockets.dll

System.Threading.Overlapped, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.Overlapped.dll

System.Net.NameResolution, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Net.NameResolution.dll

System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Core.dll

System.Console, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Console.dll

System.Security.Principal.Windows, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Principal.Windows.dll

System.Security.Claims, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Claims.dll

System.Threading.ThreadPool, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Threading.ThreadPool.dll

System.Security.Cryptography.Encoding, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Security.Cryptography.Encoding.dll

System.Diagnostics.StackTrace, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Diagnostics.StackTrace.dll

System.Reflection.Metadata, Version=1.4.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Reflection.Metadata.dll

System.Collections.Immutable, Version=1.2.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.Collections.Immutable.dll

System.IO.MemoryMappedFiles, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.8\System.IO.MemoryMappedFiles.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.
```
