### ISSUE TITLE
Report on results of kwsch's pull requests

### ISSUE THREAD

**Issue by BeyondTheHorizon** [architdate/PKHeX-Plugins#9]
I am aware these pull requests aren't quite ready to be submitted to the master branch, but I found some interesting information I thought I'd let you know about, plus I was impatient. I copied the raw files of kwsch's pull requests into my local copy and further edited the SmogonSetLists.cs file to include the Smogon urls for previous generations. Here is the edited file:

[SmogonSetList.zip](https://github.com/architdate/PKHeX-Plugins/files/2797191/SmogonSetList.zip)

Testing, I noticed a few quirks. Here they are:
1. Gen 3 and onward pkm files now collect the appropriate Smogon sets, but Gen 1 and 2 returns the following error. I believe this may be because of things like Abilities being absent from Gen 2, and Held Items being absent from Gen 1:

![pkhex error](https://user-images.githubusercontent.com/20503303/51762621-22befa00-20c8-11e9-92ad-3b510925b52e.png)

2. Species names have a "-" symbol after them e.g. "Venusaur-" instead of "Venusaur".
3. There is no space between EVs/IVs and the stats e.g. It says "31HP" instead of "31 HP".
4. Gens 3 and 4 return the ability as "items". Gen 5 and onwards return the appropriate ability correctly.

**Comment by architdate** [comment]
Thanks for this, if possible could you send a Pull request to kaphotics' fork so that if merged it shows up in the same pull request? Thanks.

**Comment by BeyondTheHorizon** [comment]
A pull request of the changes made to SmogonSetList.cs?

**Comment by kwsch** [comment]
I merged it in already (changes to GetBaseURL)
https://github.com/architdate/PKHeX-Plugins/commit/6eaff6c60b04871ed6d654cf28954d1703279ef2

**Comment by BeyondTheHorizon** [comment]
Thank you, Kurt.

**Comment by architdate** [comment]
This seems to be handled

**Comment by BeyondTheHorizon** [comment]
No, I'm still having problems. Trying to gen Smogon sets for Gens 1 and 2 returns the same error as before, and trying to gen for Gens 3 and above returns "Invalid lines detected" (the "-" symbol after the species name) and no longer copies to the clipboard.
